// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrtXLLHMWZnpSdXj-Yjsl17q7w6WIVJ_U',
    appId: '1:790268977249:web:ff32f88a405379b9908a20',
    messagingSenderId: '790268977249',
    projectId: 'mminikadimlar',
    authDomain: 'mminikadimlar.firebaseapp.com',
    storageBucket: 'mminikadimlar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2enePLGpkZvme4K34XBJ93VdowKgp0xU',
    appId: '1:790268977249:android:3b95cb57edd76bbd908a20',
    messagingSenderId: '790268977249',
    projectId: 'mminikadimlar',
    storageBucket: 'mminikadimlar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbWg8tnCcuq00otM2OegEyQ20GbcXwqiQ',
    appId: '1:790268977249:ios:c1b9be2fbdc3ee43908a20',
    messagingSenderId: '790268977249',
    projectId: 'mminikadimlar',
    storageBucket: 'mminikadimlar.firebasestorage.app',
    iosBundleId: 'com.example.minikadimlar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbWg8tnCcuq00otM2OegEyQ20GbcXwqiQ',
    appId: '1:790268977249:ios:c1b9be2fbdc3ee43908a20',
    messagingSenderId: '790268977249',
    projectId: 'mminikadimlar',
    storageBucket: 'mminikadimlar.firebasestorage.app',
    iosBundleId: 'com.example.minikadimlar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrtXLLHMWZnpSdXj-Yjsl17q7w6WIVJ_U',
    appId: '1:790268977249:web:752cd872d97f3629908a20',
    messagingSenderId: '790268977249',
    projectId: 'mminikadimlar',
    authDomain: 'mminikadimlar.firebaseapp.com',
    storageBucket: 'mminikadimlar.firebasestorage.app',
  );
}
